### PR TITLE
web: check for clean build check in

### PR DESCRIPTION
**Pull request by joostjager**
This PR:
* Adds web build to the repository
* Adds CI check that forces web build to always be up to date.

Makes it easier to run circuitbreaker on platforms that do not have docker available.

### CODE REVIEW

**Comment by M1ch43lV** [comment]
The new branch works flawlessly for me using ```go build```. Great! Thank you for the fix to have the newest frontend for non-docker user environnements!

**Comment by blckbx** [comment]
Same here. No more fiddling with `yarn` on bolt.

**Comment by M1ch43lV** [comment]
I will close PR #69. With this PR no manual yarn Installation and compilation is needed.

**Comment by flyerbear** [comment]
Thank you for modifying to support environments not running docker!

I'm a bit confused about the steps to install initially using this PR. After cloning the repo, and switching to the `circuitbreaker` directory, are any additional steps necessary to build the frontend with this modification prior to `go install`?

**Comment by joostjager** [comment]
You don't need to build the frontend anymore, because it is checked into the repo.

**Comment by Ripley81** [comment]
I've re-installed the latest version (?) using the Raspibolt guide, and see my install as: 

$ circuitbreaker --version
circuitbreakerd version development

I've proceeded to enable it and start it using the guide. It's running fine.

I tried starting the web version by following the instruction: "Open http://127.0.0.1:9235/ in a browser."  but get nothing there. 

Firefox can’t establish a connection to the server at 127.0.0.1:9235.

How do I start the web version?

(I'm a noob if you didn't already know)

Thanks for your help

**Comment by blckbx** [comment]
> I tried starting the web version by following the instruction: "Open http://127.0.0.1:9235/ in a browser." but get nothing there.

RaspiBolt guide has not been updated to support the web version yet. I think we'll get there in a few days. 
Briefly looking at the changes required, you just might be missing the `--httplisten "0.0.0.0:9235"` option running from command-line or systemd service.

Related Feature Request: https://github.com/raspibolt/raspibolt/issues/1280

**Pull request merged**
